theme: jekyll-theme-minimal
title: Stacey Brandsma
description: AI Product Leader | Data Scientist | Healthcare Innovation
# description
markdown: GFM

# Professional Details
linkedin_username: stacey-brandsma
github_username: staceybrandsma
email: your.email@domain.com

# SEO settings
lang: en-US
author: Stacey Brandsma

# Google Analytics (optional)
# google_analytics: your-tracking-id

# Professional navigation
navigation:
  - title: About
    url: "#about"
  - title: Experience
    url: "#experience"
  - title: Education
    url: "#education"
  - title: Skills
    url: "#skills"
  - title: Contact
    url: "#contact"